In [2]:
import torch
import numpy as np

In [6]:
# 空の配列を作成
x = torch.empty(5,3)
print(x)

tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [7]:
x = torch.rand(5,3)
print(x)

tensor([[0.9530, 0.6409, 0.0951],
        [0.4237, 0.8163, 0.6340],
        [0.8457, 0.1486, 0.0113],
        [0.4404, 0.2442, 0.8693],
        [0.6488, 0.8975, 0.8794]])


In [9]:
torch.zeros(5,3,dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [10]:
torch.tensor([1.23,3])

tensor([1.2300, 3.0000])

In [11]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [12]:
x = torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[ 0.2437, -0.8960,  0.7919],
        [ 1.3573,  1.1112,  0.6575],
        [-0.5947,  2.8329,  1.1043],
        [-1.2682,  1.2536,  0.6758],
        [-1.6263, -0.6140, -0.0861]])


In [13]:
x = torch.arange(0,19,2)
print(x)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


In [15]:
x = torch.linspace(0,3,4)
print(x)

tensor([0., 1., 2., 3.])


In [16]:
x = torch.FloatTensor([5,6,7])
print(x)
print(x.dtype)

tensor([5., 6., 7.])
torch.float32


In [17]:
x = torch.tensor([5,6,7],dtype=torch.int)

In [18]:
print(x.dtype)

torch.int32


In [19]:
torch.manual_seed(42)
x = torch.rand(2,3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [21]:
x.dtype

torch.float32

In [22]:
x.size()

torch.Size([2, 3])

In [23]:
x.shape

torch.Size([2, 3])

In [25]:
x = torch.rand(5,3)
print(x)

tensor([[0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]])


In [26]:
y = torch.rand(5,3)
print(y)

tensor([[0.5779, 0.9040, 0.5547],
        [0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890],
        [0.2814, 0.7886, 0.5895],
        [0.7539, 0.1952, 0.0050]])


In [27]:
print(x+y)

tensor([[1.0193, 1.2009, 1.3863],
        [0.4476, 0.9038, 0.7232],
        [0.9098, 1.4936, 0.7952],
        [1.2330, 0.8639, 1.4755],
        [1.3371, 0.5329, 0.8140]])


In [29]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[1.0193, 1.2009, 1.3863],
        [0.4476, 0.9038, 0.7232],
        [0.9098, 1.4936, 0.7952],
        [1.2330, 0.8639, 1.4755],
        [1.3371, 0.5329, 0.8140]])


In [30]:
y.add_(x)
print(y)

tensor([[1.0193, 1.2009, 1.3863],
        [0.4476, 0.9038, 0.7232],
        [0.9098, 1.4936, 0.7952],
        [1.2330, 0.8639, 1.4755],
        [1.3371, 0.5329, 0.8140]])


In [31]:
print(y[:,1])

tensor([1.2009, 0.9038, 1.4936, 0.8639, 0.5329])


In [32]:
print(y[0,:])

tensor([1.0193, 1.2009, 1.3863])


In [33]:
print(y[2:,1:])

tensor([[1.4936, 0.7952],
        [0.8639, 1.4755],
        [0.5329, 0.8140]])


In [36]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [38]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([2.7504])
2.750434637069702


In [39]:
a = torch.ones(3)
print(a)

tensor([1., 1., 1.])


In [40]:
b = a.numpy()
print(b)

[1. 1. 1.]


In [41]:
a.add_(3)
print(a)
print(b)

tensor([4., 4., 4.])
[4. 4. 4.]


In [42]:
a = np.ones(3)
print(a)

[1. 1. 1.]


In [43]:
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1.], dtype=torch.float64)


In [44]:
a = torch.arange(1,4,1,dtype=torch.float)
print(a)

tensor([1., 2., 3.])


In [45]:
a.mean()

tensor(2.)

In [46]:
a.sum()

tensor(6.)

In [48]:
a.max()

tensor(3.)

In [49]:
a = torch.tensor([1,2,3],dtype=torch.float)
b = torch.tensor([4,5,6],dtype=torch.float)

print(torch.add(a,b).sum())

tensor(21.)


In [50]:
import math
a = torch.tensor([math.radians(30),math.radians(60),math.radians(90)])

In [51]:
print(torch.sin(a))
print(torch.cos(a))
print(torch.tan(a))
print(torch.asin(a))
print(torch.tanh(a))

tensor([0.5000, 0.8660, 1.0000])
tensor([ 8.6603e-01,  5.0000e-01, -4.3711e-08])
tensor([ 5.7735e-01,  1.7321e+00, -2.2877e+07])
tensor([0.5511,    nan,    nan])
tensor([0.4805, 0.7807, 0.9172])


In [53]:
a = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float)
b = torch.tensor([[1,2],[3,4],[5,6]],dtype=torch.float)

In [55]:
torch.mm(a,b)

tensor([[22., 28.],
        [49., 64.]])

In [56]:
print(a@b)

tensor([[22., 28.],
        [49., 64.]])


In [58]:
x = torch.ones(2,2,requires_grad = True)

In [59]:
y = x + 2

In [60]:
z = (y**2).mean()

In [61]:
z.backward()
print(x.grad)

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])
